FROM quay.io/training-org/training-repo/library/node:16 AS appbuild

LABEL version="1.0"
LABEL description="To Do List application builder"

# ENV REACT_APP_API_HOST=http://localhost:3000
ENV REACT_APP_API_HOST=""

USER 0

COPY . /tmp/todo-frontend

RUN cd /tmp/todo-frontend && \
    npm cache clean --force && \
    npm --loglevel verbose install --no-package-lock  && \
    npm run build

# https://github.com/sclorg/nginx-container
FROM quay.io/sclorg/nginx-126-c10s

WORKDIR /usr/share/nginx/html


LABEL version="1.0"
LABEL description="To Do List application front-end"
LABEL creationDate="2017-12-25"
LABEL updatedDate="2021-05-19"

COPY nginx.conf /etc/nginx
	
COPY --from=appbuild /tmp/todo-frontend/build /usr/share/nginx/html

#ADD PORT EXPOSER
EXPOSE 8080
USER nginx

#ADD USER

CMD ["nginx", "-g", "daemon off;"]
