apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc-claim-{cuid}
  labels:
    app: mysql-db-{cuid}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
